### ISSUE TITLE
multi edgex instance support

### ISSUE THREAD

**Issue by huiwq1990** [openyurtio/yurt-edgex-manager#10]
1）If I want to deploy multi edgex instaces in same namespace, `yurt-edgex-manager` generate solid uniteddeployments, like `edgex-core-consul`. Could we generate uniteddeployments with nodepool name as prefix?
2) Config crd edgex is too complex , if I want add a ui component, I need write complex yamls. As a demo below:
```yaml
apiVersion: device.openyurt.io/v1alpha1
kind: EdgeX
metadata:
  name: edgex-sample-$WORKER_NODEPOOL
spec:
  version: hanoi
  poolname: $WORKER_NODEPOOL
  additinalservices:
  - metadata:
      name: edgex-device-virtual
    spec:
      type: NodePort
      selector:
        app: edgex-device-virtual
      ports:
      - name: http
        port: 49990
        protocol: TCP
        targetPort: 49990
        nodePort: 30090
  - metadata:
      name: edgex-device-rest
    spec:
      type: NodePort
      selector:
        app: edgex-device-rest
      ports:
      - name: http
        port: 49986
        protocol: TCP
        targetPort: 49986
```

3) `yurt-edgex-manager` use `EdgeXConfig` as template, if deploy multi instances, error occur as below:
```yaml
  Version:        jakarta
Status:
  Conditions:
    Last Transition Time:  2022-03-10T08:59:37Z
    Message:               Service "edgex-core-consul" is invalid: spec.ports[0].nodePort: Invalid value: 30850: provided port is already allocated
    Reason:                ServiceProvisioningFailed
    Severity:              Warning
    Status:                False
    Type:                  Ready
    Last Transition Time:  2022-03-10T08:59:37Z
    Status:                True
    Type:                  ConfigmapAvailable
    Last Transition Time:  2022-03-10T08:59:37Z
    Message:               Service "edgex-core-consul" is invalid: spec.ports[0].nodePort: Invalid value: 30850: provided port is already allocated
    Reason:                ServiceProvisioningFailed
    Severity:              Warning
    Status:                False
    Type:                  ServiceAvailable
  Initialized:             true
```
 
Could we use helm as template render, and user can custom select deploy which component and set component values.
