### ISSUE TITLE
[Design] New edgex API

### ISSUE THREAD

**Issue by lwmqwer** [openyurtio/yurt-edgex-manager#32]
\kind design
The edge additional components config is too complex.
Propose replace with below API and set defaults for users as much as possible

```YAML
apiVersion: device.openyurt.io/v1alpha1
kind: EdgeX
metadata:
  name: edgex-sample-beijing
  namespace: "beijing"
spec:
  version: jakarta
  poolname: beijing
  componets:
  - name: edgex-core-consul
     labels:
     - core: True
     - database: true
    image: openyurt/consul:1.10.3
    port: 8500
    mountPath: 
     - "/consul/config"
     - "/consul/data"
  - name: edgex-core-data
    image:  openyurt/core-data:2.1.0
```
